### ISSUE TITLE
Blur not working on Applications Overview - Pop!_OS 21.04

### ISSUE THREAD

**Issue by TermoZour** [aunetx/blur-my-shell#117]
The Applications view shows the default grey background when the extension is enabled. It works properly on another Pop!_OS 21.04 installation on another PC.

The Extensions manager shows this error: `Main.overview._updateBackgroundsBlur is not a function`
`gnome-shell --version` shows: GNOME Shell 3.38.4

I tried restarting the shell with CTRL+F2 then "r" but the same issue occurs. Enabling or disabling the overview button in the extension settings doesn't change anything.
![image](https://user-images.githubusercontent.com/16005294/127954156-3ee644b5-ef05-46e8-b622-f5df0789cb30.png)
Even though it shows up as "disabled" the extension blurs my top panel properly.

**Comment by aunetx** [comment]
That's weird that it does not work for your pc... Are you using the same cosmic version on the two installs?

**Comment by akashnigam08** [comment]
I am also getting the same issue on Pop OS 21.04

**Comment by TermoZour** [comment]
Yes. I recently reinstalled Pop on my PC as well. They have the same stock dot files. It's weird that at some point they started working again. It just didn't report the error and it blurred the overview correctly. 

How can I check some logs just in case it happens again so I can provide more info?

**Comment by aunetx** [comment]
Sorry, I don't really have the motivation to try and hunt bugs right now...

But for the moment, what you could do is give me the output in looking glass (`alt+f2`, type `lg`) of the following call:

```js
Main.overview._updateBackgroundBlur
```

After the extension is enabled (and when it's crashed, ofc)

**Comment by maplehobo** [comment]
Experiencing the same issue on Pop 21.04

**Comment by aunetx** [comment]
Could you try to install Blur my Shell from github with the latest commit from branch `pre_40`?

After install, it is better to logout/login to make sure the shell correctly load the extension.

**Comment by Freeplayg** [comment]
Honestly not sure if I did it right, but now I'm getting `this.update_backgrounds_blur is not a function` error

**Comment by DeicPro** [comment]
> Could you try to install Blur my Shell from github with the latest commit from branch `pre_40`?
> 
> After install, it is better to logout/login to make sure the shell correctly load the extension.

I did it, relogged and now I get this: `this.update_backgrounds_blur is not a function`


Looking Glass:
```
>>> this.update_backgrounds_blur is not a function
r(1) = <exception SyntaxError: unexpected token: identifier>
```

Tried on Ubuntu 21.04 GNOME 3.38 both Xorg and Wayland.

And the mainline version of this extension on extensions.gnome.org works fine (except the UI glitches if Overview check is enabled, in the pre_40 branch occurs too) in the moment that you install it, but when relogging shows the error message of the first post and doesn't work as expected.

**Comment by aunetx** [comment]
Sorry for this, I misspelled a function name when trying to fix this, I'm really ashamed...

Could you try latest commit from `pre_40`?

**Comment by aunetx** [comment]
I'm honestly a bit lost, this is unknown territory for me... Pop_os is great, except when it comes to supporting it with extensions :(
If this happens again, could you tell me here please? And if everything is great now, I will try to push a new release -- when I find the time to do so :)

**Comment by shungo27** [comment]
Moving Main.overview._updateBackgroundsBlur = function () {...} outside of var OverviewBlur = class OverviewBlur {...} fixed this error.

**Comment by ezoterikwa** [comment]
> Modify overview.js.
> 
> ```
>     set_sigma(s) {
>         sigma = s;
>         // Main.overview._updateBackgroundsBlur();
>     }
> 
>     set_brightness(b) {
>         brightness = b;
>         // Main.overview._updateBackgroundsBlur();
>     }
> ```
> 
> Raspberry Pi OS Lite 64bit Gnome 3.38 Blur my shell 22

Thanks, kind man, it worked on debian 11 gnome 3.38.5

**Comment by aunetx** [comment]
This should not happen for recent version of the extension, as the entire code path has been updated. Please reopen if needed.
